version: '3.7'

services:
    backend:
        container_name: backend
        image: kingkongbilly/backend:1.0
        networks:
            - app-network
        depends_on:
            - database
        environment:
          - DB_ADRESS=database
          - DB_USER=usr
          - DB_PASSWORD=pwd
    database:
        container_name: database
        image: kingkongbilly/database:1.0
        environment:
          - POSTGRES_USER=usr
          - POSTGRES_DB=db
          - POSTGRES_PASSWORD=pwd
        networks: 
          - app-network

    httpd:
        container_name: httpd
        image: kingkongbilly/httpd:1.0
        networks: 
            - app-network
        ports:
            - "80:80"
        depends_on:
            - database
            - backend
        volumes:
            - db_data:/var/lib/postgresql/data
    devops-front:
        container_name: devops-front
        image: kingkongbilly/devops-front:1.0
        networks: 
            - app-network
        ports:
            - "80:80"
        depends_on:
            - database
            - backend
            - httpd
        
networks:
    app-network: 
volumes:
  db_data:
