---
# tasks file for roles/launch-database
- name: Create a postgres container
  community.docker.docker_container:
    network_mode: "app-network"
    name: database
    image: "kingkongbilly/tp-devops-database:latest"
    volumes:
      - db_data:/var/lib/postgresql/data
    env:
      POSTGRES_DB: "db"
      POSTGRES_USER: "usr"
      POSTGRES_PASSWORD: "pwd"
