FROM httpd:2.4.58

COPY ./public-html/ /usr/local/apache2/htdocs/
#COPY C:\Users\ceift\Documents\CPE\S8\devops-lesson\TP1\httpd.conf http-server:/usr/local/apache2/conf/
COPY ./httpd.conf /usr/local/apache2/conf/
