---
# tasks file for roles/launch-app

- name: Launch app container
  community.docker.docker_container:
    network_mode: "app-network"
    name: backend
    image: "kingkongbilly/tp-devops-simple-api:latest"
    # ports:
    #   - "8080:8080"
    env:
      DB_URL: "jdbc:postgresql://database:5432/db"
      DB_USER: "usr"
      DB_PASSWORD: "pwd"
