---
# tasks file for roles/launch-proxy

- name: Launch proxy container
  community.docker.docker_container:
    network_mode: "app-network"
    name: httpd
    image: "kingkongbilly/tp-devops-httpd:latest"
    ports:
      - "8080 :80"
