- hosts: all
  gather_facts: false
  become: true
  vars_files:
    - secrets.yml
  roles:
    - install-requirement
    - docker
    - create-network
    - launch-database
    - launch-app
    - launch-proxy
    - launch-frontend
